name: Benchmarks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
    quickly:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Validate composer.json and composer.lock
              run: composer validate --strict
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-php-
            - name: Install PHP 8.4
              run: sudo apt-add-repository ppa:ondrej/php -y && sudo apt-get install -y -q php8.4 php8.4-curl php8.4 php8.4-dom php8.4 php8.4-mbstring
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Script (php-actions)
              run: php benchmark.php
          
